/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

rootProject.name = "debridav"

if (file("../nzb-streamer").exists()) {
    includeBuild("../nzb-streamer")
}
