{
 "title": "Rclone Mounts",
 "tags": [ "rclone" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rclone Mount Status",
   "type": "stat",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rclone_up", "legendFormat": "{{user_agent}} ({{volume}})" }
   ]
  },
  {
   "title": "Fatal Errors",
   "type": "stat",
   "gridPos": { "h": 12, "w": 8, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rclone_fatal_error", "legendFormat": "{{user_agent}} ({{volume}})" }
   ]
  },
  {
   "title": "Retry Errors",
   "type": "stat",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rclone_retry_error", "legendFormat": "{{user_agent}} ({{volume}})" }
   ]
  },
  { "title": "Transfer Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Total Transfers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(rclone_transfers_total[5m])",
     "legendFormat": "{{user_agent}} ({{volume}})"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(rclone_bytes_transferred_total[5m])",
     "legendFormat": "{{user_agent}} ({{volume}})"
    }
   ]
  },
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(rclone_errors_total[5m])", "legendFormat": "{{user_agent}} ({{volume}})" }
   ]
  },
  {
   "title": "Elapsed Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "rclone_elapsed_time_seconds", "legendFormat": "{{user_agent}} ({{volume}})" }
   ]
  }
 ]
}