CREATE TABLE nzb_document (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    files JSONB NOT NULL
);

CREATE TABLE nzb_streamable_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT NOT NULL REFERENCES nzb_document(id) ON DELETE CASCADE,
    path VARCHAR NOT NULL,
    total_size BIGINT NOT NULL,
    start_volume_index INT NOT NULL,
    start_offset_in_volume BIGINT NOT NULL,
    continuation_header_size BIGINT NOT NULL,
    end_of_archive_size BIGINT NOT NULL
);

CREATE INDEX idx_nzb_streamable_file_document_id ON nzb_streamable_file(document_id);
