CREATE TABLE IF NOT EXISTS config_override (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prop_key   VARCHAR(255) NOT NULL UNIQUE,
    prop_value TEXT,
    sensitive  BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);
