CREATE TABLE nzb_import (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usenet_download_id  BIGINT REFERENCES usenet_download(id) ON DELETE SET NULL,
    name                VARCHAR(255) NOT NULL,
    category            VARCHAR(255),
    status              VARCHAR(30)  NOT NULL DEFAULT 'QUEUED',
    archive_type        VARCHAR(30),
    error_message       TEXT,
    files               JSONB,
    size                BIGINT,
    created_at          TIMESTAMP WITH TIME ZONE,
    updated_at          TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_nzb_import_status ON nzb_import (status);
