{
 "title": "DebriDav",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "DebriDav", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Streams",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    { "expr": "debridav_bitrate", "legendFormat": "{{provider}}::{{file}}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "Cpu usage" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "sum(jvm_memory_used_bytes)", "legendFormat": "Memory usage" }
   ]
  },
  { "title": "Library", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Library Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    { "expr": "debridav_library_size", "legendFormat": "Files: {{source}}" }
   ]
  },
  {
   "title": "Easynews",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debridav_library_metrics{provider=\"EASYNEWS\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Premiumize",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debridav_library_metrics{provider=\"PREMIUMIZE\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Real-Debrid",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debridav_library_metrics{provider=\"REAL_DEBRID\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Torbox",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "debridav_library_metrics{provider=\"TORBOX\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_database_size_bytes{datname=\"debridav\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    { "expr": "hikaricp_connections", "legendFormat": "Connection pool size" },
    { "expr": "hikaricp_connections_active", "legendFormat": "Active connections" },
    { "expr": "hikaricp_connections_pending", "legendFormat": "Pending connections" }
   ]
  },
  {
   "title": "Large objects size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "pg_largeobjects_sum", "legendFormat": "Size" }
   ]
  },
  { "title": "Rate limiting", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Rate limiters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "resilience4j_ratelimiter_available_permissions",
     "legendFormat": "Available permissions: {{name}}"
    },
    {
     "expr": "resilience4j_ratelimiter_waiting_threads",
     "legendFormat": "Waiting threads: {{name}}"
    }
   ]
  },
  { "title": "Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Total cache size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "debridav_cache_size", "legendFormat": "Cache size" }
   ]
  },
  {
   "title": "Number of items in cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    { "expr": "debridav_cache_items", "legendFormat": "Cached items" }
   ]
  },
  {
   "title": "Rclone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true
  },
  {
   "title": "Rclone errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    { "expr": "rate(rclone_errors_total[5m])", "legendFormat": "Errors" }
   ]
  },
  {
   "title": "Rclone transfer rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(rclone_bytes_transferred_total[5m]) / 300",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}